import { body, param } from "express-validator";

export const updateFooterSectionSchema = [
  param("id")
    .exists()
    .withMessage("El ID es obligatorio")
    .custom((val) => /^\d+$/.test(val))
    .withMessage("El ID debe ser un número válido")
    .toInt(),
  body("textLogo")
    .exists()
    .withMessage("El campo textLogo es obligatorio")
    .isString()
    .withMessage("El textLogo debe ser una cadena de texto")
    .notEmpty()
    .withMessage("El textLogo no puede estar vacío"),
  body("description")
    .exists()
    .withMessage("El campo description es obligatorio")
    .isString()
    .withMessage("La description debe ser una cadena de texto")
    .notEmpty()
    .withMessage("La description no puede estar vacía"),
  body("phone")
    .exists()
    .withMessage("El campo phone es obligatorio")
    .isString()
    .withMessage("El phone debe ser una cadena de texto")
    .notEmpty()
    .withMessage("El phone no puede estar vacío"),
  body("iconPhone")
    .exists()
    .withMessage("El campo iconPhone es obligatorio")
    .isString()
    .withMessage("El iconPhone debe ser una cadena de texto")
    .notEmpty()
    .withMessage("El iconPhone no puede estar vacío"),
  body("email")
    .exists()
    .withMessage("El campo email es obligatorio")
    .isString()
    .withMessage("El email debe ser una cadena de texto")
    .notEmpty()
    .withMessage("El email no puede estar vacío"),
  body("iconEmail")
    .exists()
    .withMessage("El campo iconEmail es obligatorio")
    .isString()
    .withMessage("El iconEmail debe ser una cadena de texto")
    .notEmpty()
    .withMessage("El iconEmail no puede estar vacío"),
  body("address")
    .exists()
    .withMessage("El campo address es obligatorio")
    .isString()
    .withMessage("La address debe ser una cadena de texto")
    .notEmpty()
    .withMessage("La address no puede estar vacía"),
  body("iconAddress")
    .exists()
    .withMessage("El campo iconAddress es obligatorio")
    .isString()
    .withMessage("El iconAddress debe ser una cadena de texto")
    .notEmpty()
    .withMessage("El iconAddress no puede estar vacío"),
  body("hours")
    .exists()
    .withMessage("El campo hours es obligatorio")
    .isString()
    .withMessage("Las hours deben ser una cadena de texto")
    .notEmpty()
    .withMessage("Las hours no pueden estar vacías"),
  body("iconHours")
    .exists()
    .withMessage("El campo iconHours es obligatorio")
    .isString()
    .withMessage("El iconHours debe ser una cadena de texto")
    .notEmpty()
    .withMessage("El iconHours no puede estar vacío")
];